# NumPy and statistics

# Statistics
Statistics is the discipline that studies the collection, organization, displaying, analysing, interpretation and presentation of data. Statistics is a branch of Mathematics that is recommended to be a prerequisite for data science and machine learning. 

# Data 
What is data? Data is any set of characters that is gathered and translated for some purpose, usually analysis. It can be any character, including text and numbers, pictures, sound, or video. If data is not put in a context, it doesn't make any sense to a human or computer. To make sense from data we need to work on the data using different tools.

The work flow of data analysis, data science or machine learning starts from data. Data can be provided from some data source or it can be created. There are structured and unstructured data.

# Statistics Module
The Python statistics module provides functions for calculating mathematical statistics of numerical data. The module is not intended to be a competitor to third-party libraries such as NumPy, SciPy, or proprietary full-featured statistics packages aimed at professional statisticians such as Minitab, SAS and Matlab. It is aimed at the level of graphing and scientific calculators.

# Numpy
NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with arrays.


In [2]:
import numpy as np

In [5]:
print(np.__version__)
print(dir(np))

1.26.4
['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_exte

# Creating numpy array 

creating int numoy arrays

In [6]:
python_list = [1,2,3,4,5]

print(type(python_list))
print(python_list)

two_dimensional_list = [[0,1,2], [2,3,4], [5,6,7]]

print(two_dimensional_list)

numpy_array_from_list = np.array(python_list)
print(type(numpy_array_from_list))
print(numpy_array_from_list)

<class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [2, 3, 4], [5, 6, 7]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


# Creating float numpy arrays

In [7]:
python_list = [1,2,3,4]

numpy_array_from_list = np.array(python_list, dtype = float)
print(numpy_array_from_list)

[1. 2. 3. 4.]


Creating Boolean numpy arrays

In [8]:
numpy_bool_array = np.array([0,1,-1,0,0], dtype = bool)
print(numpy_bool_array)

[False  True  True False False]


# Creating multidimensional array using numpy

In [9]:
two_dimensional_list = [[0,1,2],[3,4,5],[6,7,8]]

numpy_two_dimensional_arr = np.array(two_dimensional_list)
print(numpy_two_dimensional_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Converting numpy array to list

In [12]:
np_to_list = numpy_array_from_list.tolist()
print(type(np_to_list))
print('One dimensional list:',np_to_list)
print('Tow dimensional list:',numpy_two_dimensional_arr.tolist())

<class 'list'>
One dimensional list: [1.0, 2.0, 3.0, 4.0]
Tow dimensional list: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


# Creating numpy array form tuple

In [13]:
python_tuple = (1,2,3,4,5)
print(type(python_tuple))
print('python_tuple:', python_tuple)

numpy_array_from_tuple = np.array(python_tuple)
print(type(numpy_array_from_tuple))
print('Numpy array form tuple:', numpy_array_from_tuple)

<class 'tuple'>
python_tuple: (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
Numpy array form tuple: [1 2 3 4 5]


# Shape of numpy array
The shape method provides the shape of the array as a tuple. The first is the row and the second is the column. If the array is just one dimensional it returns the size of the array.

In [19]:
arr = np.array([1,2,3,4,5])
print(arr)
print('shape of array:',arr.shape)

numpy_two_dimensional_arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
print('shape of numpy tow dimensional array:', numpy_two_dimensional_arr.shape)

three_by_four_arr = np.array([[1,2,3,4],
[4,5,6,7],
[7,8,9,10]]
)

print(three_by_four_arr)
print('shape of three by four array:', three_by_four_arr.shape)

[1 2 3 4 5]
shape of array: (5,)
shape of numpy tow dimensional array: (3, 3)
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
shape of three by four array: (3, 4)


In [23]:
arr3d = np.array([[[1,2,3,4],
[4,5,6,7]],[[6,7,8,9],[10,11,22,33]]])
print(arr3d)
print(arr3d.shape)

[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 6  7  8  9]
  [10 11 22 33]]]
(2, 2, 4)


# Data type of numpy array
Type of data types: str, int, float, complex, bool, list, None

In [25]:
int_lists = [-3,-2,-1,0,1,2,3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype = float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)

[-3 -2 -1  0  1  2  3]
int32
[-3. -2. -1.  0.  1.  2.  3.]
float64


# Size of a numpy array
In numpy to know the number of items in a numpy array list we use size

In [27]:
print(numpy_array_from_list.size)
print(numpy_two_dimensional_arr.size)

4
9


# Mathematical Operation using numpy
NumPy array is not like exactly like python list. To do mathematical operation in Python list we have to loop through the items but numpy can allow to do any mathematical operation without looping. Mathematical Operation:

1. Addition (+)
2. Subtraction (-)
3. Multiplication (*)
4. Division (/)
5. Modules (%)
6. Floor Division(//)
7. Exponential(**)

Addition

In [28]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_plus_original = numpy_array_from_tuple + 10
print(ten_plus_original)

original array:  [1 2 3 4 5]
[11 12 13 14 15]


Subtraction

In [29]:
numpy_array_from_list = np.array([1,2,3,4,5])
print('original array:', numpy_array_from_list)
ten_minus_original = numpy_array_from_list - 10
print(ten_minus_original)

original array: [1 2 3 4 5]
[-9 -8 -7 -6 -5]


Multiplication

In [30]:
numpy_array_from_list = np.array([1,2,3,4,5])
print('original array:', numpy_array_from_list)
ten_time_original = numpy_array_from_list*10
print(ten_time_original)

original array: [1 2 3 4 5]
[10 20 30 40 50]


Modulus

In [31]:
modulus_of_arr = numpy_array_from_list % 3
print(modulus_of_arr)

[1 2 0 1 2]


Floor Division

In [32]:
floor_division_array = numpy_array_from_list // 10
print(floor_division_array)

[0 0 0 0 0]


Exponetioal

In [34]:
expo_arr = numpy_array_from_list ** 2
print(expo_arr)

[ 1  4  9 16 25]


# Checking data types

In [35]:
numpy_int_arr = np.array([1,2,3,4])
numpy_float_arr = np.array([1.1, 2.0,3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1,2,3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int32
float64
bool


# Converting Types
We can convert the data types of numpy array

1. int to Float

In [36]:
numpy_int_arr = np.array([1,2,3,4], dtype = 'float')
numpy_int_arr 

array([1., 2., 3., 4.])

2. Float to int

In [37]:
numpy_int_arr = np.array([1.,2.,3.,4.], dtype = 'int')
numpy_int_arr

array([1, 2, 3, 4])

3. Int to boolean

In [38]:
np.array([-3,-3,0,1,2,3], dtype = 'bool')

array([ True,  True, False,  True,  True,  True])

4. int to str

In [41]:
numpy_float_arr.astype('int').astype('str')

array(['1', '2', '3'], dtype='<U11')

# Multi_dimensional Arrays

In [42]:
two_dimensional_arr = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(type(two_dimensional_arr))
print(two_dimensional_arr)
print('Shape:', two_dimensional_arr.shape)
print('Size:', two_dimensional_arr.size)
print('Data type:', two_dimensional_arr.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data type: int32


# Getting items from a numpy array

In [43]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row:', third_row)

First row: [1 2 3]
Second row: [4 5 6]
Third row: [7 8 9]


In [44]:
first_colum = two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('First column:', first_colum)
print('Second column:', second_column)
print('Third column:', third_column)
print(two_dimension_array)

First column: [1 4 7]
Second column: [2 5 8]
Third column: [3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
